version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: newsletter-postgres
    environment:
      POSTGRES_DB: newsletter_kcs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"  # Port externe 5433 pour éviter les conflits
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - newsletter-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d newsletter_kcs"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin (Interface d'administration PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: newsletter-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@newsletter-kcs.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - newsletter-network
    depends_on:
      - postgres
    restart: unless-stopped

  # MailHog (pour les emails de test)
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: newsletter-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - newsletter-network
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  newsletter-network:
    driver: bridge
