version: '3.8'

services:
  # Application Next.js Newsletter KCS
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: newsletter-app
    environment:
      # Base de données
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: newsletter_kcs
      DB_USER: postgres
      DB_PASSWORD: postgres123

      # OpenAI (à configurer avec votre vraie clé)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-your-openai-api-key-here}

      # Email (MailHog pour les tests)
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SMTP_FROM: "newsletter@kcs.local"

      # Next.js
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    ports:
      - "3001:3000"  # Port externe 3001 pour éviter les conflits
    volumes:
      - ./app/public/uploads:/app/public/uploads  # Persistance des uploads
    networks:
      - newsletter-network
    depends_on:
      postgres:
        condition: service_healthy
      mailhog:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: newsletter-postgres
    environment:
      POSTGRES_DB: newsletter_kcs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"  # Port externe 5433 pour éviter les conflits
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - newsletter-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d newsletter_kcs"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin (Interface d'administration PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: newsletter-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@newsletter-kcs.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - newsletter-network
    depends_on:
      - postgres
    restart: unless-stopped

  # MailHog (pour les emails de test)
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: newsletter-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - newsletter-network
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  newsletter-network:
    driver: bridge
