version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: newsletter-postgres
    environment:
      POSTGRES_DB: newsletter_kcs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db-simple.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - newsletter-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MailHog (pour les emails de test)
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: newsletter-mailhog
    ports:
      - "1026:1025"  # SMTP
      - "8026:8025"  # Web UI
    networks:
      - newsletter-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  newsletter-network:
    driver: bridge
